-- Encoder subagent transcripts for the Axiom lab schema.

CREATE SCHEMA IF NOT EXISTS lab;
GRANT USAGE ON SCHEMA lab TO postgres, service_role, anon, authenticated;

CREATE TABLE IF NOT EXISTS lab.agent_transcripts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL,
    agent_id TEXT,
    tool_use_id TEXT NOT NULL,
    subagent_type TEXT NOT NULL,
    prompt TEXT,
    description TEXT,
    response_summary TEXT,
    transcript JSONB,
    orchestrator_thinking TEXT,
    message_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    uploaded_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_agent_transcripts_session
    ON lab.agent_transcripts(session_id, created_at);
CREATE INDEX IF NOT EXISTS idx_agent_transcripts_type
    ON lab.agent_transcripts(subagent_type);
CREATE INDEX IF NOT EXISTS idx_agent_transcripts_created
    ON lab.agent_transcripts(created_at DESC);

ALTER TABLE lab.agent_transcripts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS anon_read ON lab.agent_transcripts;
CREATE POLICY anon_read ON lab.agent_transcripts
    FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS authenticated_read ON lab.agent_transcripts;
CREATE POLICY authenticated_read ON lab.agent_transcripts
    FOR SELECT TO authenticated USING (true);

GRANT SELECT ON lab.agent_transcripts TO anon, authenticated;
GRANT ALL ON lab.agent_transcripts TO postgres, service_role;
GRANT USAGE, SELECT ON SEQUENCE lab.agent_transcripts_id_seq TO postgres, service_role;
